### ISSUE TITLE
[1.19.2] Class not found crash

### ISSUE THREAD

**Issue by itsdinkd** [CafeteriaGuild/DeepMobLearning-Refabricated#118]
```
net.minecraft.util.crash.CrashException: Ticking block entity
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:879) ~[server-intermediary.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cek000$modifiedRunLoop(MinecraftServer.java:7385) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/I18n
	at dev.nathanpb.dml.simulacrum.block.chamber.BlockEntitySimulationChamber.updateSimulationText(BlockEntitySimulationChamber.kt:141) ~[dmlsimulacrum-0.5.9-BETA+1.19.2-a05399d751920e1.jar:?]
	at dev.nathanpb.dml.simulacrum.block.chamber.BlockEntitySimulationChamber.access$updateSimulationText(BlockEntitySimulationChamber.kt:43) ~[dmlsimulacrum-0.5.9-BETA+1.19.2-a05399d751920e1.jar:?]
	at dev.nathanpb.dml.simulacrum.block.chamber.BlockEntitySimulationChamber$Companion.tick(BlockEntitySimulationChamber.kt:365) ~[dmlsimulacrum-0.5.9-BETA+1.19.2-a05399d751920e1.jar:?]
	at dev.nathanpb.dml.simulacrum.block.chamber.BlockSimulationChamber.getTicker$lambda-1(BlockSimulationChamber.kt:76) ~[dmlsimulacrum-0.5.9-BETA+1.19.2-a05399d751920e1.jar:?]
	at net.minecraft.WorldChunk$EntityLoaderclass_5563.redirect$cen000$checkProcessBEs(WorldChunk.java:784) ~[server-intermediary.jar:?]
	at net.minecraft.WorldChunk$EntityLoaderclass_5563.tick(WorldChunk.java:660) ~[server-intermediary.jar:?]
	at net.minecraft.WorldChunk$EntityLoaderclass_5564.tick(WorldChunk.java:714) ~[server-intermediary.jar:?]
	at net.minecraft.world.World.tickBlockEntities(World.java:456) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:376) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:875) ~[server-intermediary.jar:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resource.language.I18n
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.13.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at dev.nathanpb.dml.simulacrum.block.chamber.BlockEntitySimulationChamber.updateSimulationText(BlockEntitySimulationChamber.kt:141) ~[dmlsimulacrum-0.5.9-BETA+1.19.2-a05399d751920e1.jar:?]
	at dev.nathanpb.dml.simulacrum.block.chamber.BlockEntitySimulationChamber.access$updateSimulationText(BlockEntitySimulationChamber.kt:43) ~[dmlsimulacrum-0.5.9-BETA+1.19.2-a05399d751920e1.jar:?]
	at dev.nathanpb.dml.simulacrum.block.chamber.BlockEntitySimulationChamber$Companion.tick(BlockEntitySimulationChamber.kt:365) ~[dmlsimulacrum-0.5.9-BETA+1.19.2-a05399d751920e1.jar:?]
	at dev.nathanpb.dml.simulacrum.block.chamber.BlockSimulationChamber.getTicker$lambda-1(BlockSimulationChamber.kt:76) ~[dmlsimulacrum-0.5.9-BETA+1.19.2-a05399d751920e1.jar:?]
	at net.minecraft.WorldChunk$EntityLoaderclass_5563.redirect$cen000$checkProcessBEs(WorldChunk.java:784) ~[server-intermediary.jar:?]
	at net.minecraft.WorldChunk$EntityLoaderclass_5563.tick(WorldChunk.java:660) ~[server-intermediary.jar:?]
	at net.minecraft.WorldChunk$EntityLoaderclass_5564.tick(WorldChunk.java:714) ~[server-intermediary.jar:?]
	at net.minecraft.world.World.tickBlockEntities(World.java:456) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:376) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:875) ~[server-intermediary.jar:?]
```

log https://gist.github.com/itsdinkd/d6cf0cc2fea367e1e24714319567c97f

**Comment by SomeAspy** [comment]
Can Confirm. See: https://mclo.gs/hgXdu2Y (this is in the All Of Fabric 6 modpack.)

**Comment by Linguardium** [comment]
https://github.com/CafeteriaGuild/DeepMobLearning-Refabricated/blob/ea663d72c4867f182a605f5de14d9dab359d556c/simulacrum/src/main/kotlin/dev/nathanpb/dml/simulacrum/block/chamber/BlockEntitySimulationChamber.kt#L17

oh no, someone is using client classes 

https://github.com/CafeteriaGuild/DeepMobLearning-Refabricated/blob/ea663d72c4867f182a605f5de14d9dab359d556c/simulacrum/src/main/kotlin/dev/nathanpb/dml/simulacrum/block/chamber/BlockEntitySimulationChamber.kt#L365

inside of a !world.isClient check

**Comment by Luligabi1** [comment]
Fixed on 0.5.10-BETA+1.19.2, will be up on CurseForge and Modrinth soon.

**Comment by Luligabi1** [comment]
never mind, I'll have to rewrite a lot of stuff for this to be properly fixed _yay..._

**Comment by itsdinkd** [comment]
> never mind, I'll have to rewrite a lot of stuff for this to be properly fixed _yay..._
 sorry 😞

**Comment by TheNickmaster21** [comment]
I have experienced a crash that I believe is related to this issue. I have attached a crash log but I am open to opening a new issue if it is not the same root cause. We are using All of Fabric 6 1.4.1 on a multiplayer world. The crash occurred when I put Polymer Clay into a Simulation Chamber. We get a crash loop with the same error whenever the server tries restarting. 

[crash-2023-02-12_10.03.01-server.txt](https://github.com/CafeteriaGuild/DeepMobLearning-Refabricated/files/10716378/crash-2023-02-12_10.03.01-server.txt)

**Comment by Luligabi1** [comment]
Hey everyone, I apologize for all the issues and how long I've been delaying a proper fix. It'll take some time to develop a perfect fix, but meanwhile I've released `0.5.11-BETA+1.19.2`. This version will fix the crashes, at the cost of no translation support for the text on the Simulation Chamber (hence why it's not a perfect fix).

**Comment by itsdinkd** [comment]
> Simulation

Ty for the quick temp fix. updating pack now. ill be on the lookout for the permanent one.
