### ISSUE TITLE
Crashes on DML 1.20.1

### ISSUE THREAD

**Issue by iamlite** [CafeteriaGuild/DeepMobLearning-Refabricated#143]
It seems every time I start the loot fabricator for overworld matter, my game will brick up. Only way to get back in is to remove the mod and re-add it. Can be replicated by just putting overworld matter into a loot fabricator. 

-- Block entity being ticked --
Details:
	Name: dml-refabricated:loot_fabricator // dev.nathanpb.dml.blockEntity.BlockEntityLootFabricator
	Block: Block{dml-refabricated:loot_fabricator}[facing=north]
	Block location: World: (-1120,110,913), Section: (at 0,14,1 in -70,6,57; chunk contains blocks -1120,-64,912 to -1105,319,927), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,-64,512 to -1025,319,1023)
	Block: Block{dml-refabricated:loot_fabricator}[facing=north]
	Block location: World: (-1120,110,913), Section: (at 0,14,1 in -70,6,57; chunk contains blocks -1120,-64,912 to -1105,319,927), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,-64,512 to -1025,319,1023)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Luligabi1** [comment]
Can you post the entire log file? There's not much to track the cause here

**Comment by Luligabi1** [comment]
Seems to be caused by [Variant Shield](https://www.curseforge.com/minecraft/mc-mods/variant-tiered-shields-fabric)'s [RemoveOffHandItemTaskMixin](https://github.com/xanthian/variant_shields/blob/1.20/src/main/java/net/xanthian/variantshields/mixin/RemoveOffHandItemTaskMixin.java). 

DML's only envolvment here is attempting to create an instance of an entity, required to generate its loot. My theory is that said entity generated with a shield in hand, triggering the mixin's target in some unexpected way. The log says it's an invalid mixin, so I don't think DML is at fault here. Try opening an issue for this on their repository for further help. Thanks for reporting!
